### PR TITLE
Created a page for the bitcoinxt docker image.

### PR DESCRIPTION
**Pull request by Removed-5an**
As requested by @mikehearn on reddit, this commit adds a new page describing the docker image that's available. Let me know if there's something you'd like me to change.

### CODE REVIEW

**Comment by mikehearn** [comment]
Does it really make sense to have a web page just for two sentences? This should probably be on the apt page, no? Or maybe we should convert the apt page into a general purpose Linux page?

**Comment by Removed-5an** [comment]
I was wondering the same thing... The apt page also doesn't really make sense as docker isn't related. And making it a general purpose Linux page also doesn't work either as docker images can run on OSX, Windows as well.

Maybe there's a way to make the docker page feel less empty. Anyway I'm not sure what the best place is. Would you prefer to have it on the apt page?

**Comment by mikehearn** [comment]
Yes, but your Docker image is Linux only isn't it. As the dockerfile just invokes apt, let's stick it on the apt page.

**Comment by Removed-5an** [comment]
No this docker image can run on any machine that supports docker. Ubuntu is just the base docker image, that's why I can use linux commands. I'll make modifications to add it to the apt page.

**Comment by Removed-5an** [comment]
Made the change to add everything to the apt page.

**Comment by mikehearn** [comment]
Thanks!

**Pull request merged**
