### PR TITLE
Remove country flags for languages. 

### LINKED ISSUE #48: Remove country flags
Languages know no borders, so the country flags where selecting language should be removed.

Suggest replacing it with the name of the language, in the language itself, like bitcoincash.org does. We need a solution that supports many languages.

@chaintip 1 year

### PR DESCRIPTION
**Pull request by kbsezginel**
@chaintip fixes #48

### CODE REVIEW

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#48](http://github.chaintip.org/bitcoinxt/website/issues/48) first, @kbsezginel will claim the `0.00879166 BCH`| `~  13.55 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/6) and all future tips to the issue.

**Comment by dagurval** [comment]
Thanks for working on this.

When you just remove the flags, what's left is just random letters with awkward padding. It's even harder to tell that it's for language selection, so not really an improvement.

lang

Issue #48 suggests an alternative:

> Suggest replacing it with the name of the language, in the language itself, like bitcoincash.org does. 

Other solutions are also welcomed.

**Comment by baldwindc** [comment]
Alternative solution submitted here: https://github.com/bitcoinxt/website/pull/53

**Comment by dagurval** [comment]
This won't go in, but I appreciate the PR @kbsezginel @chaintip

**Comment by chaintip** [comment]
@kbsezginel, you've [been sent](https://explorer.bitcoin.com/bch/address/bitcoincash:qqh0ld49czsswywdq03rylnh47xuxmxaevquynzs32) `0.006736 BCH`| `~  10.18 USD` by @dagurval via [chaintip](http://www.chaintip.org).

**Comment by dgenr8** [comment]
Closing in favor of #54

**Comment by kbsezginel** [comment]
Thank you!

**Pull request closed without merging**
