### PR TITLE
Translation into Russian

### PR DESCRIPTION
**Pull request by Har01d**
Перевод сайта bitcoinxt.software на русский язык.
It is expected that Russian translation will be in a directory called "/ru/".

### CODE REVIEW

**Comment by josephcastan** [comment]
What about switching mechanism? Do we need language icons somewhere?

Also maybe we should replace absolute links with relative ones, so it requires less changes and is more error-prone.

**Comment by Har01d** [comment]
Yes, currently there is no switching between languages.

Regarding the links there are two options:
1. To use absolute links
2. To include a `<base>` tag and to use relative links (which would be different for CSS/JS and translated HTML files, since they are in the different parent directories)

Because it's pretty easy to make mistakes implementing either of them, I just went with the first one :)

P.S. I’m not sure if I edited _layout.html.erb and index.html.erb correctly since I haven’t worked with this CMS.

**Comment by josephcastan** [comment]
Is base really needed? I couldn't find rationale for introducing it, it just seems to duplicate the default behavior of the browser. Plus it can interfere with anchor links.

If I get around to adding the language icons tomorrow I will also test your edits.

**Comment by Har01d** [comment]
The point is taken, I suppose you are right, it seems like I've somehow confused a subdirectory with a subdomain :)
Since I haven't tested it, it would be helpful if you will.

**Comment by ghost1542** [comment]
@Har01d Do you think you are available to keep the Russian translations updated per chance? Speaking of my experience with bitcoin.org, keeping translations up to date soon becomes a real challenge except when there's long term translators on board.

Also, ideally it's very useful to have one template to generate all translated pages, in such a way that it's easier to track changes and outdated translations, as well as to keep consistency between translations. I am not sure what is possible with the Serve static website generator.

**Comment by Har01d** [comment]
@saivann, I was going to propose that to @mikehearn. As I've already said to him, I'm not a Git wizard, but if I'm currently doing the things right, I suppose I could maintain the Russian version of the site (at least while it's relatively small). I should mention that I worked in pair with a professional editor to be sure the texts would be perfect :)

I agree with you on the templates, because I believe that besides Russian, the site should be translated at least into Chinese.

**Comment by gill3s** [comment]
Being writing the french translation right now, I was looking for the right translation mechanism. Maybe we coud use Transifex ?

**Comment by georgengelmann** [comment]
Having a system like Transifex (or maybe Launchpad) for translations would be great.

**Comment by josephcastan** [comment]
Somebody then should integrate something like this into the site. Having simple copies is fine for now when we have just a few pages, but will certainly become a problem down the road.

**Comment by josephcastan** [comment]
1. The menu in Russian version is way too long. Even in 1920 px it doesn't fit.
2. Menu links should probably be relative in default.html.erb and root links for both logo and Welcome should be "index.html". Probably should change in the English version too. By the way, your English version seems outdated, did you base your changes on some earlier version?

**Comment by gill3s** [comment]
re : outdated version I don't see the "Who's on board" section in the master repository

**Comment by josephcastan** [comment]
Is this some Github caching issue? The #17 pull request was merged and closed, but now I can't see it in the main branch...

**Comment by georgengelmann** [comment]
That's not the only missing PR

**Comment by Har01d** [comment]
@NxtChg, I've fixed the menu problem. But I'm not sure if it was a good idea to reduce the font size in the main CSS file, because it reduces the size in English version as well as in Russian. Maybe we need a different CSS file for Russian version.

I've also removed italics subset of the Roboto font since it wasn't used.
And changed links back to relative.

>  By the way, your English version seems outdated, did you base your changes on some earlier version?

I don't know why the master branch doesn't include the latest commits, but I translated the "Who's onboard" page as well as the others.

**Comment by josephcastan** [comment]
I don't think reducing font size is the correct approach to this... Especially if it affects other versions too.

Can you rewrite menu text to make it more compact?

Also not sure about removing fonts...

**Comment by Har01d** [comment]
@NxtChg, ok, I've introduced a separate CSS class for the Russian menu bar.
Statistically, both Russian words and sentences are 15-20% longer than English, so I don't think you can fight the statistics by making words more compact :)
Concerning the fonts: I haven't met italicized text in the project.

**Comment by mikehearn** [comment]
Looks good! Apologies for the out of date master branch. I pushed my local copy to github.

The menu bar is kind of broken still. We need to change the links to be relative not absolute as suggested above.

**Comment by mikehearn** [comment]
Also yeah we should probably have a little Russian flag or a piece of text on the English version so people can find it. Otherwise who would know it is there?

**Comment by josephcastan** [comment]
> Also yeah we should probably have a little Russian flag or a piece of text on the English version so people can find it. Otherwise who would know it is there?

Yeah, I've downloaded a bunch of flag icons, still trying to find a place for them on the page. This design needs some serious rethinking...

**Comment by Har01d** [comment]
@mikehearn, I've already changed the links back to relative, it's in this commit: https://github.com/Har01d/bitcoinxt-website-ru/commit/b4a9ce6549543391a5238e39e31bafc04e382a27
Can anyone make a screenshot of the menu bar? I've tested it using Web Inspector in Safari, maybe it looks different in other browsers, so we should reduce the font size even more. There is another option - I could use "Главная" ("Homepage") instead of "Добро пожаловать" ("Welcome") - it's much shorter, but I don't know if it's ok.

**Comment by mikehearn** [comment]
Yeah "homepage" is fine.

**Comment by josephcastan** [comment]
@Har01d Icons are ready, do you mind if I take your edits and integrate them into a single commit? It all became a bit messy, I am afraid to forget some link somewhere. And then Mike will just have to do a single merge for both. Only replace the Homepage item first.

Also @mikehearn, what do you think about replacing the top XT icon with the one from here: https://www.reddit.com/r/bitcoinxt/comments/3jf6tp/should_xts_branding_look_more_familiar_like_this/

Current one is a bit ugly and also conflicts with the Haskell logo.

**Comment by mikehearn** [comment]
I'd rather not start changing the branding in big ways now. It's not perfect but then neither is Bitcoin's own logo.

**Comment by josephcastan** [comment]
It was just a few weeks, it's easier to do it now than in a year. It's arbitrary anyway.

The logo clearly rips off the Haskell's logo, couple of guys already posted about it, so it's embarrassing, and the lambda makes no sense in Bitcoin whatsoever.

Also I am not proposing to "change branding in big ways", just replace the small top icon in the site's header.

**Comment by josephcastan** [comment]
Created #20 with translated version and language icons in one package. Updated some links to work correctly. So close this one and merge #19 and #20.

**Comment by mikehearn** [comment]
This was merged

**Pull request closed without merging**
