### PR TITLE
Update: SEO, community links, accessibility

### PR DESCRIPTION
**Pull request by georgengelmann**
- Improvements for search engines (titles for all anchors, meta descriptions, robots.txt, XML sitemap)
- Links to Freenode Web IRC (because most people don't have an IRC client installed) and the Bitcoin XT community on reddit
- Adds navigation with accesskeys
- Move all style options to the stylesheet

### CODE REVIEW

**Comment by mikehearn** [comment]
Should the sitemap really specify weekly? Doesn't that mean it'll take a week for any changes we make to show up in search engines?

**Comment by ghost1542** [comment]
FWIW, I am not sure if the sitemap file is an improvement, in that if it is not generated automatically, some pages will eventually be missing inside it, and it probably doesn't make any positive difference while the website has only a few pages, none are hidden or buried inside a deep hierarchy of pages.

@chmod755 Regarding the anchors' titles, is there a known benefit for using them? In your previous PR, it seemed like this was about some HTML5 good practice, but upon reading, it seems like this [doesn't improve accessibility](https://silktide.com/i-thought-title-text-improved-accessibility-i-was-wrong/) or impact SEO in practice. The only situation where it seems to have some moderate utility is when there is useful additional information that isn't already displayed as plain text on the website (e.g. when link texts are cut), which I think doesn't seem to be the case here in general.

Edit: The freenode web and reddit links are a good idea!

**Comment by georgengelmann** [comment]
@mikehearn 

"How frequently the page is likely to change. This value provides general information to search engines and may not correlate exactly to how often they crawl the page."

"Please note that the value of this tag is considered a hint and not a command. Even though search engine crawlers may consider this information when making decisions, they may crawl pages marked "hourly" less frequently than that, and they may crawl pages marked "yearly" more frequently than that. Crawlers may periodically crawl pages marked "never" so that they can handle unexpected changes to those pages."

Source: http://www.sitemaps.org/protocol.html

@saivann 

An automated sitemap would definitely be better.

Re: title, there is no agreement on whether they help in SEO, but at least they can provide more information in a tooltip, like here:

<a href="https://github.com/bitcoinxt/gitian.sigs" title="Gitian signatures and assertions for XT">deterministic builds</a>

or here:

<a href="https://medium.com/@octskyward/crash-landing-f5cc19908e32" title="Crash landing — Medium">experiencing reliability problems as a result</a>

**Comment by ghost1542** [comment]
Well either way the extra title tags are not harmful AFAIK, so cool if some can have some utility. Perhaps those only repeating the same text already in the anchor or not really providing any extra value can be removed, but that's really not a huge issue I think. Regarding the sitemap, I guess it's all up to Mike to consider the likeliness that it doesn't get updated (coincidentally, a new page is currently being submitted).

**Comment by mikehearn** [comment]
Merged, thanks!

**Pull request closed without merging**
