### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by EchterAgo**
As promised, here are the German translation files

### CODE REVIEW

**Comment by dagurval** [comment]
Again, great work, thanks! :-). 

I think we should decide on a sort order for languages. If I have to pick one, I'll go for the [same as wikipedia](https://ux.stackexchange.com/a/17065). In that case, Deutsch goes before русский.

Could you change that? I could also do it in a separate PR.

**Comment by EchterAgo** [comment]
Sure, I also found some typos I want to go over first. Don't merge yet.

**Comment by EchterAgo** [comment]
Updated

**Review by dagurval — APPROVED** [review]

**Comment by dagurval** [comment]
Awesome! Your is now up on https://bitcoinxt.software/ :-)

**Pull request merged**
