### PR TITLE
Integrate jekyll-multiple-languages-plugin for translations

### LINKED ISSUE #49: Support internationalization
We want the website to be in multiple languages, but easily maintainable. Right now, translation is done by copy/pasting the whole website and then translating the copy.

This is impossible to maintain. We need proper internationalization support. So either:

- Find a jekyll plugin that adds internationalization, and fully implement it.
- Or if jekyll doesn't provide a solution, replace jekyll with something that does.

@chaintip 365 days

### PR DESCRIPTION
**Pull request by EchterAgo**
@chaintip fixes #49

### CODE REVIEW

**Comment by chaintip** [comment]
If this pull request is merged to fix issue [#49](http://github.chaintip.org/bitcoinxt/website/issues/49) first, @EchterAgo will claim the `0.02197916 BCH`| `~  33.43 USD` [bounty](http://github.chaintip.org/chaintip/bounties/issues/7) and all future tips to the issue.

**Comment by EchterAgo** [comment]
Had to upgrade Jekyll to 3.0 because the plugin needs it. Also the Russian translation seems to be a bit out of sync and needs some fixes.

**Comment by EchterAgo** [comment]
Test build:

[testbuild.zip](https://github.com/bitcoinxt/website/files/1733711/testbuild.zip)

**Comment by dagurval** [comment]
This is great work! Thanks for working on this.

I found one issue, comparing this and [bitcoinxt.software](https://bitcoinxt.software), the layout on the FAQ is different. Also, the w3 validator found two errors on the FAQ page that weren't there before:

validator

Could you fix that?

**Comment by EchterAgo** [comment]
Thanks for the review, will fix it tomorrow. The original page also had
some errors, but I'm sure I also introduced some new ones. What I still
wonder is if it would be better to split the strings into pages. Like
having a separate yml file for each page.

**Comment by EchterAgo** [comment]
Another thing I'm unsure about is my handling of the baseurl parameter in
config.yml, I couldn't get it to work without changing it because otherwise
I would get // in links and it would take the path as a hostname. Maybe
something changed here in jekyll.

Also the Gemfile.lock, im not sure if I should check this change in. This
is my first time working with Ruby.

**Comment by EchterAgo** [comment]
Also, I didn't change the onboarding file as it is marked obsolete. If this
is needed too I will do so ASAP.

**Comment by EchterAgo** [comment]
Oh, I'll also make a German translation as soon as this is merged.

**Comment by EchterAgo** [comment]
Updated to fix the FAQ formatting issue.

**Comment by EchterAgo** [comment]
Fixed the validation problems. It is kind of a hacky fix because I didn't want to change the layout but still wanted to use the for loop in the file, which means I had to create an additional empty div/section element at the end :\

**Review by dagurval — APPROVED** [review]

**Comment by chaintip** [comment]
Nice work @EchterAgo! Your pull request has been merged and the [bounty](http://github.chaintip.org/chaintip/bounties/issues/7) of `0.02197916 BCH`| `~  33.16 USD` has been sent to your wallet.

**Comment by dagurval** [comment]
> What I still wonder is if it would be better to split the strings into pages. Like
having a separate yml file for each page.

One file is fine IMO. The site doesn't have much content and we can change it later if it becomes an issue.

> Also, I didn't change the onboarding file as it is marked obsolete. If this
is needed too I will do so ASAP.

We just keep it to avoid link rot. It's linked to by various discussion forums and historically interesting. Best to leave without translation.

As for Gemfile.lock, I don't know. 

I prefer your solution for the FAQ to keep the loop.

Thanks again for the fix! It's a big improvement.

**Pull request merged**
