### PR TITLE
Update for russian translation (apt.html)

### PR DESCRIPTION
**Pull request by Har01d**
Based on https://github.com/bitcoinxt/website/pull/24
This text is more consistent with the rest of the translation, while https://github.com/bitcoinxt/website/pull/26 has some drawbacks. 

P.S. @zander, рад видеть кого-то ещё разговаривающего на русском здесь :)
Я поправил в вашем тексте несколько ошибок и поменял некоторые термины (в остальном переводе везде используется "нода" вместо "узла", "daemon" в смысле программы имеет устоявшийся прямой перевод "демон").

### CODE REVIEW

**Comment by zander** [comment]
I'm not Russian, someone else did the translation for me (via-via on IRC). I just made the merge request.
He warned me that the technical bits were a bit off, so I'm fine with a more technical person offering a translation instead.

Thanks!

**Comment by georgengelmann** [comment]
Can you guys add a meta description to the Russian pages? It's just a short description of the content (ideally between 80-160 characters)

Line 3: https://github.com/bitcoinxt/website/blob/master/views/welcome.html.erb

**Comment by mikehearn** [comment]
Meta descriptions aren't used by anything, as far as I know. I think maybe some of this SEO stuff is not really worth it.

**Comment by mikehearn** [comment]
Hah, I got really confused for a moment because I didn't notice that Chrome was translating the Russian back into English and I thought there was no translation for apt.html ..... thanks!

**Pull request merged**
