### PR TITLE
Fix title and description

### PR DESCRIPTION
**Pull request by dagurval**
Partial revert of #58

### CODE REVIEW

**Comment by dagurval** [comment]
@EchterAgo I didn't notice it until the updates went live, but the change in #58 broke the title. I don't know if this is the correct way to fix it, but it works. Thoughts?

**Comment by EchterAgo** [comment]
I also just noticed this, will investigate.

**Comment by EchterAgo** [comment]
I think this is a bug in jekyll-multiple-languages-plugin. After the revert it is exactly how the plugin recommends to do translation in templates:

https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin#54-i18n-in-templates

Yet it warns that the keys are missing. Maybe we should provide a fallback title/description? Or just ignore the warning?

**Comment by EchterAgo** [comment]
Anyway, I think this revert is correct and should be merged.

**Comment by dagurval** [comment]
Thanks for investigating @EchterAgo

**Pull request merged**
