### PR TITLE
CSS cleanup

### PR DESCRIPTION
**Pull request by ghost1542**
Live preview: (Merged)

Although more cleanup can certainly be done, this pull request is a beginning.
- Drop many unused CSS code, global variables and dependencies
- Reorganize code to better meet SASS conventions
- Move global variables and mixup declarations in modules
- Move CSS files under partials and only use one CSS file to import them all
- Reduce the number of CSS files and use more explicit file names.
- Beautify CSS to apply a consistent syntax everywhere
- Include normalize.css

### CODE REVIEW

**Comment by Har01d** [comment]
You should also remove

`<link rel="stylesheet" href="/stylesheets/component.css">`
`<link rel="stylesheet" href="/stylesheets/main.css">`

from /views/ru/layouts/default.html.erb

**Comment by ghost1542** [comment]
@Har01d Indeed, new commit added, thanks!

**Comment by mikehearn** [comment]
Thanks!!

**Comment by mikehearn** [comment]
Thanks! I noticed the en/ru picker is still kind of busted on mobile though.....

**Comment by ghost1542** [comment]
Yes, this was just a cleanup with no fixes whatsoever for that kind of issue. Yes, the top logo / menu / languages would need to be improved for mobiles, perhaps with a typical hamburger menu or similar.

**Pull request merged**
